logging:
  level:
    root: INFO
  file:
    path: ./logs/survey-service.log

server:
  port: 8084
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/survey/v3/api-docs
spring:
  jpa:
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MY_SQL_HOST}:3306/${MY_SQL_DATABASE} # mysql container name
    username: ${MY_SQL_USER}
    password: ${MY_SQL_PASSWORD}
  application:
    name: survey-service
